### PR TITLE
Null safety compatibility

### PR DESCRIPTION
**Pull request by edufolly**
Upgrading the plugin to null safety.

### CODE REVIEW

**Comment by allanwolski** [comment]
+1

**Comment by fogaiht** [comment]
@edufolly brasil_fields package has the same validators, i'm using it

**Comment by edufolly** [comment]
@fogaiht I tried to use brasil_fields, but I faced some issues. Now I create a new package https://github.com/edufolly/folly_fields

**Comment by leonardocaldas** [comment]
@edufolly new version published.

**Pull request closed without merging**
